# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A flexible and fast mixed model toolbox for genetic analysis.'
url:              https://limix.github.io
baseurl:          /

author:
  name:           'Danilo Horta'
  url:            https://github.com/horta

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/limix/limix.github.io
