# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Limix
tagline:          'Genetic analysis toolbox'
description:      'A flexible and fast mixed model toolbox for genetic analysis.'
url:              https://limix.github.io
baseurl:          /

author:
  name:           'Danilo Horta'
  url:            https://github.com/horta

paginate:         5

# Custom vars
version:          1.0.12

github:
  repo:           https://github.com/limix/limix
