highlighter:      rouge
permalink: /:title/

# Setup
title:            Limix
tagline:          'Genetic analysis toolbox'
description:      'A flexible and fast mixed model toolbox for genetic analysis.'
url:              https://limix.github.io
baseurl:          ""

author:
  name:           'Danilo Horta'
  url:            https://github.com/horta

paginate:         5

github:
  repo:           https://github.com/limix/limix

documentation:
          url: https://limix.readthedocs.io
